import * as Tabs from '@radix-ui/react-tabs'
import { CopyIcon } from '#root/pages/components/icons/copy.svg.jsx'
import type { PropsWithChildren, ReactNode } from 'react'
import { Text } from '@kibamail/owly/text'

interface SdkCodeSnippetsProps {
  footer?: ReactNode
  sdks: { name: string; code: string }[]
}

export function SdkCodeSnippets({
  footer,
  sdks,
  children,
}: PropsWithChildren<SdkCodeSnippetsProps>) {
  return (
    <Tabs.Root defaultValue={sdks?.[0]?.name}>
      <div className="w-full flex flex-col rounded-2xl border kb-border-tertiary">
        <div className="min-h-13 py-3 flex items-center justify-between rounded-t-2xl kb-background-secondary border-b kb-border-tertiary px-3">
          <Tabs.List className="flex items-center gap-2">
            {sdks.map((sdk) => (
              <Tabs.TabsTrigger
                value={sdk.name}
                key={sdk.name}
                className="cursor-pointer text-(--content-tertiary) font-medium border-transparent data-[state=active]:border data-[state=active]:border-solid data-[state=active]:border-(--border-tertiary) data-[state=active]:text-(--content-secondary) rounded-lg px-2 py-1"
              >
                <Text>{sdk.name}</Text>
              </Tabs.TabsTrigger>
            ))}
          </Tabs.List>

          <CopyIcon className="kb-content-secondary w-6 h-6" />
        </div>

        <div className="w-full overflow-x-auto bg-[#212121]">
          {sdks.map(({ name, code }) => (
            <Tabs.TabsContent value={name} key={name}>
              {/* biome-ignore lint/security/noDangerouslySetInnerHtml: code snippets are generated by us on the server, and not by users, so this is safe. */}
              <div dangerouslySetInnerHTML={{ __html: code }} />
            </Tabs.TabsContent>
          ))}
        </div>

        <div className="min-h-13 py-3 flex items-center rounded-b-2xl justify-between kb-background-secondary border-t kb-border-tertiary px-3">
          {footer}
        </div>
      </div>
    </Tabs.Root>
  )
}
