---
# Default variables for PM2 installation
# PM2 version to install
pm2_version: "latest"

# Application user and group
pm2_app_user: kibamail
pm2_app_group: kibamail

# PM2 application names
pm2_app_name: "kibamail-app"
pm2_worker_name: "kibamail-worker"

# Deployment path
pm2_base_deploy_path: /var/www/kibamail

# Environment settings
pm2_infisical_env: "staging"
