app:
  hosts:
    app-prod:
      ansible_host: 10.1.0.1

dragonfly:
  hosts:
    dragonfly-prod:
      ansible_host: 10.1.0.2

mail_primary:
  hosts:
    mail1-prod:
      ansible_host: 10.1.0.3

mail_secondary:
  hosts:
    mail2-prod:
      ansible_host: 10.1.0.4

mail_proxy:
  hosts:
    mail-proxy-prod:
      ansible_host: 10.1.0.5

mysql_master:
  hosts:
    mysql-master-prod:
      ansible_host: 10.1.0.6

mysql_slave:
  hosts:
    mysql-slave-prod:
      ansible_host: 10.1.0.7

monitoring:
  hosts:
    monitoring-prod:
      ansible_host: 10.1.0.8

mysql:
  children:
    mysql_master:
    mysql_slave:

mail:
  children:
    mail_primary:
    mail_secondary:
    mail_proxy:

production:
  children:
    app:
    dragonfly:
    mail:
    mysql:
    monitoring:
