name: server tests

on:
  pull_request:
    branches: [ main ]

jobs:
  server-tests:
    name: server tests
    runs-on: ubuntu-latest
    env:
      # App configuration
      ACME_DIRECTORY_URL: ${{ secrets.ACME_DIRECTORY_URL }}
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_URL: ${{ secrets.APP_URL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      NODE_ENV: "test"
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}

      # Database configuration
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Redis configuration
      REDIS_URL: ${{ secrets.REDIS_URL }}

      # File uploads/S3 configuration
      FILE_UPLOADS_ACCESS_KEY: ${{ secrets.FILE_UPLOADS_ACCESS_KEY }}
      FILE_UPLOADS_ACCESS_SECRET: ${{ secrets.FILE_UPLOADS_ACCESS_SECRET }}
      FILE_UPLOADS_ENDPOINT: ${{ secrets.FILE_UPLOADS_ENDPOINT }}
      FILE_UPLOADS_PORT: ${{ secrets.FILE_UPLOADS_PORT }}
      FILE_UPLOADS_BUCKET: ${{ secrets.FILE_UPLOADS_BUCKET }}
      FILE_UPLOADS_REGION: ${{ secrets.FILE_UPLOADS_REGION }}

      # OAuth configuration
      OAUTH_GITHUB_CALLBACK_URL: ${{ secrets.OAUTH_GITHUB_CALLBACK_URL }}
      OAUTH_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
      OAUTH_GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
      GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
      OAUTH_GOOGLE_CALLBACK_URL: ${{ secrets.OAUTH_GOOGLE_CALLBACK_URL }}
      OAUTH_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH_GOOGLE_CLIENT_ID }}
      OAUTH_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH_GOOGLE_CLIENT_SECRET }}

      # Commerce providers
      COMMERCE_PROVIDER_PAYSTACK_PUBLIC_KEY: ${{ secrets.COMMERCE_PROVIDER_PAYSTACK_PUBLIC_KEY }}
      COMMERCE_PROVIDER_PAYSTACK_SECRET_KEY: ${{ secrets.COMMERCE_PROVIDER_PAYSTACK_SECRET_KEY }}
      COMMERCE_PROVIDER_STRIPE_PUBLIC_KEY: ${{ secrets.COMMERCE_PROVIDER_STRIPE_PUBLIC_KEY }}
      COMMERCE_PROVIDER_STRIPE_SECRET_KEY: ${{ secrets.COMMERCE_PROVIDER_STRIPE_SECRET_KEY }}

      # Mail server configuration
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      SMTP_MAIL_FROM: ${{ secrets.SMTP_MAIL_FROM }}
      MAILPIT_API_URL: ${{ secrets.MAILPIT_API_URL }}

      # MTA configuration
      MTA_ACCESS_TOKEN: ${{ secrets.MTA_ACCESS_TOKEN }}
      MTA_AUTHENTICATOR_PORT: ${{ secrets.MTA_AUTHENTICATOR_PORT }}
      MTA_INJECTOR_PORT: ${{ secrets.MTA_INJECTOR_PORT }}
      MTA_INJECTOR_URL: ${{ secrets.MTA_INJECTOR_URL }}
      MTA_LOG_PROCESSOR_PORT: ${{ secrets.MTA_LOG_PROCESSOR_PORT }}
      HARAKA: ${{ secrets.HARAKA }}

      # Other configuration
      EVENT_TRACKING_DOMAIN: ${{ secrets.EVENT_TRACKING_DOMAIN }}
      MMDB_DOWNLOAD_URL: ${{ secrets.MMDB_DOWNLOAD_URL }}
      SECRETS_STORE_TOKEN: ${{ secrets.SECRETS_STORE_TOKEN }}
      SECRETS_STORE_URL: ${{ secrets.SECRETS_STORE_URL }}

      # Doppler configuration
      DOPPLER_CONFIG: ${{ secrets.DOPPLER_CONFIG }}
      DOPPLER_ENVIRONMENT: ${{ secrets.DOPPLER_ENVIRONMENT }}
      DOPPLER_PROJECT: ${{ secrets.DOPPLER_PROJECT }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - uses: ./.github/actions/install-dependencies

      - uses: ./.github/actions/setup-docker

      - uses: ./.github/actions/run-command
        with:
          name: run server tests with coverage
          command: pnpm ci:test:server:coverage
