name: type checking

on:
  pull_request:
    branches: [ main ]

jobs:
  type-check:
    name: type check
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/checkout-and-cache
      - uses: ./.github/actions/setup-node-pnpm
      - uses: ./.github/actions/install-dependencies

      - uses: ./.github/actions/run-command
        with:
          name: run type checking
          command: pnpm types:check
